server:
  port: 8085

spring:
  application:
    name: spring-batch-quartz
  jpa:
    hibernate:
      ddl-auto: create
    database: postgresql
    show-sql: true
  datasource:
    url: jdbc:postgresql://localhost:5432/product_db
    username: admin
    password: admin
    driverClassName: org.postgresql.Driver
  quartz:
    job-store-type: jdbc
    jdbc:
      initialize-schema: always


  batch:
    jdbc:
      initialize-schema: always
    job:
      enabled: false

application:
  scheduler:
    cron: "0 */2 * ? * *"
